services:
  db:
    image: postgres:16
    container_name: postgres_dev_landscaping
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: landscaping
    ports:
      - "5433:5432"
    volumes:
      - pgdata_landscaping:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  pgdata_landscaping:
